tests: Improve dev_revalidate()
Commit 858744785dfa ("tests: lib: Fix dev_revalidate()") fixed the
dev_revalidate() function to wait for the block device file to exist.
This is needed but not enough to ensure that a device revalidation
completed: while the block device file exist, the device capacity may be
0 and thus we need to wait for the device capacity to ne non zero to
ensure that the device revalidation completed.

Introduce the function dev_wait_for_revalidate() to check the device
capacity and make sure that this function fails after 30s waiting for
the device capacity to be valid. cdl-tests.sh is modified to stop
execution if dev_revalidate() fails, including failures of
dev_wait_for_revalidate().

Suggested-by: Dmitry Fomichev <dmitry.fomichev@wdc.com>
Fixes: 858744785dfa ("tests: lib: Fix dev_revalidate()")
Signed-off-by: Damien Le Moal <dlemoal@kernel.org>

diff --git a/tests/scripts/test_lib b/tests/scripts/test_lib
--- a/tests/scripts/test_lib
+++ b/tests/scripts/test_lib
@@ -167,8 +167,13 @@ function dev_capacity()
 {
 	local dev="$(realpath $1)"
 	local bdev="$(basename ${dev})"
+	local bdev_capacity="/sys/block/${bdev}/size"
 
-	echo "$(cat /sys/block/${bdev}/size)"
+        if [ -f "${bdev_capacity}" ]; then
+		echo "$(cat ${bdev_capacity})"
+	else
+		echo "0"
+	fi
 }
 
 function dev_fw()
@@ -210,6 +215,23 @@ function dev_uses_hba_sat()
 	[ "${val}" != "libata" ]
 }
 
+function dev_wait_for_revalidate()
+{
+	local dev="$(realpath $1)"
+
+	for tt in {0..60}; do
+		cap=$(dev_capacity ${dev})
+		if [ "${cap}" != "0" ]; then
+			return 0
+		fi
+		sleep .5
+	done
+
+	echo "Failed to get capacity"
+
+	return 1
+}
+
 function dev_revalidate()
 {
 	local dev="$(realpath $1)"
@@ -231,13 +253,13 @@ function dev_revalidate()
 		exit_failed "Rescan ${dev} failed"
 
 	# Wait for the block device to come back
-        until [ -e /sys/block/${bdev} ]; do
-                sleep .1
-        done
+	dev_wait_for_revalidate "${dev}" || return 1
 
 	# Re-enable NCQ
 	echo 1 > /sys/block/${bdev}/device/queue_depth
 	echo 32 > /sys/block/${bdev}/device/queue_depth
+
+	return 0
 }
 
 function create_nullb()
