tests: Cleanup test script exit messages
Automatically add " --> failed", " --> skip" and " --> warning" prefix
to the message printed by exit_failed, exit_skip and exit_warning
respectively. Note that these prefixes are in lower case, to facilitate
grepping a test case result based on the final PASS, FAILED or WARNING
result added to each test case by cdl-tests.sh.

Signed-off-by: Damien Le Moal <dlemoal@kernel.org>

diff --git a/tests/scripts/test_lib b/tests/scripts/test_lib
--- a/tests/scripts/test_lib
+++ b/tests/scripts/test_lib
@@ -12,18 +12,31 @@ function test_num()
 
 function exit_skip()
 {
+	if [ $# == 1 ]; then
+		echo " --> skip: $1"
+	else
+		echo " --> skip"
+	fi
 	exit 2
 }
 
 function exit_warning()
 {
-	echo "$1"
+	if [ $# == 1 ]; then
+		echo " --> warning: $1"
+	else
+		echo " --> warning"
+	fi
 	exit 3
 }
 
 function exit_failed()
 {
-	echo "$1"
+	if [ $# == 1 ]; then
+		echo " --> failed: $1"
+	else
+		echo " --> failed"
+	fi
 	exit 1
 }
 
@@ -361,12 +374,12 @@ function test_setup()
 	# It does not make sense to compare latencies when expecting an error, as such
 	# test cases are expected to exit before reaching the supplied fio runtime.
 	if [ "$expect_error" == "1" ] && [ "$compare_latencies" == "1" ]; then
-		exit_failed " --> FAILED (invalid test case configuration)"
+		exit_failed "invalid test case configuration"
 	fi
 
 	# We only support rw=randread and rw=randwrite for now
 	if [ "$rw" != "randread" ] && [ "$rw" != "randwrite" ]; then
-		exit_failed " --> FAILED (invalid test case configuration)"
+		exit_failed "invalid test case configuration"
 	fi
 
 	# Skip non-NCQ tests on SCSI
@@ -389,23 +402,23 @@ function test_setup()
 	validate_page $dev T2A $original_T2A || {
 		echo "Uploading T2A page"
 		cdladm upload --file $original_T2A $dev || \
-			exit_failed " --> FAILED to upload T2A page"
+			exit_failed "failed to upload T2A page"
 
 		validate_page $dev T2A $original_T2A || \
-			exit_failed " --> FAILED to validate uploaded T2A page"
+			exit_failed "failed to validate uploaded T2A page"
 	}
 
 	# Only upload cdl page if it differs from the existing page
 	validate_page $dev T2B $original_T2B || {
 		echo "Uploading T2B page"
 		cdladm upload --file $original_T2B $dev || \
-			exit_failed " --> FAILED to upload T2B page"
+			exit_failed "failed to upload T2B page"
 
 		validate_page $dev T2B $original_T2B || \
-			exit_failed " --> FAILED to validate uploaded T2B page"
+			exit_failed "failed to validate uploaded T2B page"
 	}
 
-	enable_cdl $dev || exit_failed " --> FAILED to enable CDL"
+	enable_cdl $dev || exit_failed "failed to enable CDL"
 }
 
 function fio_run_time()
@@ -491,7 +504,7 @@ function analyze_log()
 
 	real_runtime="$(grep "CDL_REAL_RUNTIME: " $fiolog)"
 	if [ -z "$real_runtime" ]; then
-		exit_failed " --> FAILED (real runtime not seen in fio log)"
+		exit_failed " -->real runtime not seen in fio log"
 	fi
 
 	real_runtime=${real_runtime#CDL_REAL_RUNTIME: }
@@ -512,7 +525,7 @@ function analyze_log()
 	# This check tries to catch such cases, so that we don't accidentally
 	# PASS a test case which had I/O timeouts.
 	if [ $(echo "$real_runtime > $max_runtime" | bc) -gt 0 ]; then
-		exit_failed " --> FAILED (fio ran longer than specified)"
+		exit_failed "fio ran longer than specified"
 	fi
 
 	if [ "$expect_error" == "1" ]; then
@@ -521,21 +534,21 @@ function analyze_log()
 		# leading to no IO errors. For such case, only warn.
 		if ! fio_has_io_error "${fiolog}"; then
 			if [ "$rw" == "randwrite" ]; then
-				exit_warning " --> WARNING: fio did not see any IO error"
+				exit_warning "fio did not see any IO error"
 			else
-				exit_failed " --> FAILED (fio did not see any IO error)"
+				exit_failed "fio did not see any IO error"
 			fi
 		fi
 
 		# IO errors should be 62 (ETIME)
 		errno="$(fio_get_io_error ${fiolog})"
 		if [ "${errno}" != "62" ]; then
-			exit_failed " --> FAILED (fio saw error ${errno} instead of ETIME=62)"
+			exit_failed "fio saw error ${errno} instead of ETIME=62"
 		fi
 	else
 		# We should not have any IO error
 		if fio_has_io_error "${fiolog}"; then
-			exit_failed " --> FAILED (IO errors detected, we should not have any)"
+			exit_failed "I/O errors detected, we should not have any"
 		fi
 	fi
 
@@ -550,7 +563,7 @@ function analyze_log()
 		# difference between cdl vs no-cdl latencies
 		thresh=$(( nocdl / 2 ))
 		if [ ${cdl} -eq 0 ] || [ ${cdl} -gt ${thresh} ]; then
-			exit_warning " --> WARNING: bad average latency"
+			exit_warning "bad average latency"
 		fi
 	fi
 }
@@ -569,14 +582,14 @@ function execute_test()
 	local rw="${10}"
 
 	if [ $# -ne 10 ]; then
-		exit_failed " --> FAILED (incorrect number of arguments given)"
+		exit_failed "incorrect number of arguments given"
 	fi
 
 	test_setup "${dev}" \
 		"${T2A_file}" "${T2B_file}" \
 		"${expect_error}" "${compare_latencies}" \
 		"${ncq}" "${rw}" || \
-		exit_failed " --> FAILED (error during setup)"
+		exit_failed "error during setup"
 
 	# fio command
 	fiocmd=$(fio_common_cmdline "${dev}" "${filename}" \
@@ -586,9 +599,9 @@ function execute_test()
 	echo "Running fio:"
 	fiolog="${logdir}/$(test_num $filename)_fio.log"
 	echo "${fiocmd}"
-	eval ${fiocmd} | tee "${fiolog}" || exit_failed " --> FAILED"
+	eval ${fiocmd} | tee "${fiolog}" || exit_failed "running fio failed"
 
 	analyze_log "${fiolog}" "${expect_error}" \
 		"${compare_latencies}" "${cdl_dld}" "${rw}" || \
-		exit_failed " --> FAILED (error while analyzing fio log)"
+		exit_failed "error while analyzing fio log"
 }
